# Dockerfile for MCP Server
FROM python:3.12-slim

WORKDIR /app

# Install necessary dependencies
#    "fastmcp>=2.13.0.2",
#    "markdownify>=1.2.0",
#    "protego>=0.5.0",
#    "readabilipy>=0.3.0",
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY ./mcp_server.py /app/mcp_server.py

EXPOSE 8000

CMD ["python", "mcp_server.py"]